# ML
CUDA_VISIBLE_DEVICES=2 python train.py --emb_list embedding/cc.es.300_lince_pos_eng_spa.vec --cuda --use_crf --model_dir matrix_lang-es_pos_eng_spa_trfs_crf_lr0.1_b32_stop10 --batch_size 32 --mode linear --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --default_label NOUN --early_stop 10 --metric accu

# EL
CUDA_VISIBLE_DEVICES=2 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec --cuda --use_crf --model_dir embedded_lang-en_pos_eng_spa_trfs_crf_lr0.1_b32_stop10 --batch_size 32 --mode linear --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --default_label NOUN --early_stop 10 --metric accu

# LINEAR
CUDA_VISIBLE_DEVICES=0 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_linear_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_stop10 --batch_size 32 --mode linear --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --default_label NOUN --early_stop 10 --metric accu

# CONCAT
CUDA_VISIBLE_DEVICES=1 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_concat_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_stop10 --batch_size 32 --mode concat --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --default_label NOUN --early_stop 10 --metric accu

# ATTN_SUM
CUDA_VISIBLE_DEVICES=2 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_stop10 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --default_label NOUN --early_stop 10 --metric accu

# ATTN_SUM, BPE, CHAR
CUDA_VISIBLE_DEVICES=0 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_bpe_char_stop10 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --bpe_lang_list en es ca pt --add_char_emb --default_label NOUN --early_stop 10 --metric accu

CUDA_VISIBLE_DEVICES=3 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_bpe_char_stop10_2 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --bpe_lang_list en es ca pt --add_char_emb --default_label NOUN --early_stop 10 --metric accu

CUDA_VISIBLE_DEVICES=2 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_bpe_char_stop10_3 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --bpe_lang_list en es ca pt --add_char_emb --default_label NOUN --early_stop 10 --metric accu

CUDA_VISIBLE_DEVICES=1 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_bpe_char_stop10_4 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --bpe_lang_list en es ca pt --add_char_emb --default_label NOUN --early_stop 10 --metric accu

CUDA_VISIBLE_DEVICES=3 python train.py --emb_list embedding/crawl-300d-2M-subword_lince_pos_eng_spa.vec embedding/cc.es.300_lince_pos_eng_spa.vec embedding/cc.ca.300_lince_pos_eng_spa.vec embedding/cc.pt.300_lince_pos_eng_spa.vec embedding/glove.840B.300d.txt --cuda --use_crf --model_dir pos_attn_sum_eng_spa_trfs_crf_lr0.1_b32_en_es_ca_pt_bpe_char_stop10_5 --batch_size 32 --mode attn_sum --train_file data/lince_pos_eng_spa/train.conll --valid_file data/lince_pos_eng_spa/dev.conll --test_file data/lince_pos_eng_spa/test.conll --lr 0.1 --bpe_lang_list en es ca pt --add_char_emb --default_label NOUN --early_stop 10 --metric accu